image: maven 

variables:
   MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
   MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
cache: 
  paths:
   - .m2/repository/
   - target/

stages:
   - build
   - test
   - package
   - deploy
codebuild:
 #tags: 
  # - build
 stage: build 
 script:   
   - mvn compile 

codetest: 
 #tags: 
  # - build 
 stage: test 
 script: 
  # - mvn $MAVEN_CLI_OPTS test 
   - mvn test 
   - echo "The code has been tested" 

Codepackage: 
 #tags: 
  # - build 
 stage: package 
 script: 
   #- mvn $MAVEN_CLI_OPTS package -Dmaven.test.skip=true 
   - mvn package -Dmaven.test.skip=true 
   - echo "Packaging the code" 
 artifacts: 
  paths: 
      - target/*.war 
 only: 
   - master 

Codedeploy: 
 #tags: 
  # - build 
 stage: deploy 
 script: 
  # - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true
   - mvn package
   - mvn deploy:deploy-file -DgroupId=com.efsavage -DartifactId=hello-world -Dversion=1.11 -Dpackaging=war -Dfile=target/hello-world-1.10.war -DgeneratePom=true -DrepositoryId=mydeployment -Durl=http://34.69.178.31:8081/repository/maven-releases
  # - curl -v -u admin:admin --upload-file target/hello-world-war-1.0.65.war  http://34.69.178.31:8081/repository/maven-releases/mya-app.war   
   #- mvn deploy -Dmaven.test.skip=true -X
   - echo "installing the package in local repository" 
 only: 
   - master
